services:
  - type: web
    name: page-craft-bot
    env: python
    buildCommand: |
      pip install -r requirements.txt
      # Minimal system dependencies to save memory
      apt-get update && apt-get install -y poppler-utils
    startCommand: python main.py
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false  # This will be set manually in Render dashboard
      - key: RENDER_EXTERNAL_URL
        value: https://page-craft-bot.onrender.com  # Update this with your actual Render URL
    healthCheckPath: /health
    autoDeploy: true
