services:
  - type: web
    name: paper-craft-bot
    env: python
    buildCommand: |
      pip install -r requirements.txt
      # Install system dependencies for pdf2image
      apt-get update && apt-get install -y poppler-utils
    startCommand: python main.py
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false  # This will be set manually in Render dashboard
    healthCheckPath: /
    autoDeploy: true
